### ISSUE TITLE
Run cpp exceptions test

### ISSUE THREAD

**Issue by ryanking13** [ryanking13/pyodide-recipes#11]
- I guess it requires patching emscripten?

```
_____________________ test_cpp_exception_catching[chrome] ______________________
packages/cpp-exceptions-test/test_cpp_exceptions.py:34: in test_cpp_exception_catching
    assert (
/usr/share/miniconda/envs/pyodide-env/lib/python3.11/site-packages/pytest_pyodide/runner.py:260: in run_js
    return self.run_js_inner(code, check_code)
/usr/share/miniconda/envs/pyodide-env/lib/python3.11/site-packages/pytest_pyodide/runner.py:365: in run_js_inner
    raise JavascriptException(retval[1], retval[2])
E   pytest_pyodide.runner.JavascriptException: 9808840
----------------------------- Captured stdout call -----------------------------
JavascriptException message:  None
--------------------------- Captured stdout teardown ---------------------------
cpp-exceptions-test already loaded from default channel
No new packages to load
______________________________ test_sjlj[chrome] _______________________________
packages/cpp-exceptions-test/test_cpp_exceptions.py:60: in test_sjlj
    assert (
/usr/share/miniconda/envs/pyodide-env/lib/python3.11/site-packages/pytest_pyodide/runner.py:260: in run_js
    return self.run_js_inner(code, check_code)
/usr/share/miniconda/envs/pyodide-env/lib/python3.11/site-packages/pytest_pyodide/runner.py:365: in run_js_inner
    raise JavascriptException(retval[1], retval[2])
E   pytest_pyodide.runner.JavascriptException: Error: Dynamic linking error: cannot resolve symbol setjmp
E       at stubs.<computed> (http://127.0.0.1:38383/pyodide.asm.js:9:140062)
E       at wasm://wasm/75[121](https://github.com/ryanking13/pyodide-recipes-mirror/actions/runs/6518437551/job/17704012132#step:8:122)092:wasm-function[8]:0x1d7
E       at run (eval at executeAsyncScript (:445:26), <anonymous>:9:17)
E       at async eval (eval at executeAsyncScript (:445:26), <anonymous>:13:34)
----------------------------- Captured stdout call -----------------------------
JavascriptException message:  Dynamic linking error: cannot resolve symbol setjmp
```

**Comment by ryanking13** [comment]
matplotlib already loaded from default channel
pytest already loaded from default channel
pyodide-tblib already loaded from default channel
No new packages to load
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
Error: Dynamic linking error: cannot resolve symbol setjmp
Error: Dynamic linking error: cannot resolve symbol setjmp

matplotlib also have this issue

**Comment by agriyakhetarpal** [comment]
Hi, @ryanking13 – This error seems to persist when trying to implement an out-of-tree build for Matplotlib (see https://github.com/matplotlib/matplotlib/issues/27870):

Here are some logs that may look familiar: https://github.com/agriyakhetarpal/matplotlib/actions/runs/8206753927/job/22446917232#step:12:51.

Was there any progress with this? I am happy to help debug in case it is needed! It is to be noted that I did get the test suite running on a previous workflow run when I built Matplotlib without any compiler flags enabled: https://github.com/agriyakhetarpal/matplotlib/actions/runs/8206271096/job/22446994045, but this build came with function signature mismatches, which I'm not too fervient of debugging either (yet).

I am using roughly the same flags as the ones in the [in-tree recipe](https://github.com/pyodide/pyodide/blob/main/packages/matplotlib/meta.yaml#L25C1-L37C1), with the exception of `USE_FREETYPE` (with which it fails to find `ftstdlib.h`, i.e., FreeType's headers).

**Comment by agriyakhetarpal** [comment]
Thanks @ryanking13, I'm not sure whether it is easy to apply the patch to Emscripten manually without having a release of Pyodide come out which contains the patch. I am trying to apply this patch to where I set up Emscripten using https://github.com/mymindstorm/setup-emsdk/, in the workflow below, where it fails with the following error:

https://github.com/agriyakhetarpal/matplotlib/actions/runs/8234185665/job/22515524846

`patch: **** Can't change to directory /home/runner/work/matplotlib/matplotlib/emsdk-cache/emsdk-main/node/upstream/emscripten/ : No such file or directory`

but maybe I am missing something? The action doesn't seem to provide an easy way via environment variables to access the directory where `emcc.py` is present, i.e., the above one (I had to scourge the `tree` output for that).

**Comment by ryanking13** [comment]
I think you are doing the right thing, but the directory seems to be incorrect.

> The action doesn't seem to provide an easy way via environment variables to access the directory where emcc.py is present

After installing emscripten (=running `setup-emsdk` action), you can use one of the following commands to find the directory that contains emcc.py

1. `em-config EMSCRIPTEN_ROOT`
2. `which emcc.py` ==> strip out emcc.py from the path
3. `echo $EMSDK/upstream/emscripten`

**Comment by agriyakhetarpal** [comment]
Ah, this one worked! I might have indeed had the wrong path – I was able to apply the patch to `$EMSDK/upstream/emscripten` (https://github.com/mymindstorm/setup-emsdk looks to be low on documentation about this because I could not find these commands there).

However, it looks like the patch may not have resolved things correctly, because I now face the same error on a new workflow run: https://github.com/agriyakhetarpal/matplotlib/actions/runs/8236213133/job/22522210894 where the `setjmp` symbol cannot be resolved. All of the memory addresses are the same as the previous log(s) above.

If this is an issue coming from an incorrect application of the patch, I apologise – it would be great to revisit this (does setting up a Pyodide virtual environment alter the contents of the Emscripten directories, and doing so may have led to the same error?)

**Comment by ryanking13** [comment]
It looks like you are applying the patch when testing matplotlib not when building matplotlib. Could you try applying the patch in the build step and see if it works?

**Comment by agriyakhetarpal** [comment]
Thanks – that indeed helped! I applied the patch in the build step and the `setjmp` symbol can be resolved; the test suite starts and I suppose `import matplotlib` works. I have now returned to a function signature mismatch, however – again: https://github.com/agriyakhetarpal/matplotlib/actions/runs/8247657176/job/22556390554

**Comment by ryanking13** [comment]
Yes, `function signature mismatch` happens really often, and you need to dig into the WASM binary to find out which function is causing the issue. In Pyodide docs, we also have some tips for debugging it: https://pyodide.org/en/stable/development/debugging.html#debugging-runtimeerror-function-signature-mismatch
